<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // "Table" mode ?>
    <table cellspacing="0" cellpadding="0" width="100%" class="products-list" id="products-list">
        <thead>
            <tr>
                <th><strong><?php echo $this->__('Sku') ?></strong></th>
                <th><strong><?php echo $this->__('Name') ?></strong></th>
                <th><strong><?php echo $this->__('Qty') ?></strong></th>
                <th><strong><?php echo $this->__('Price') ?></strong></th>
                <th width="1">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_productCollection as $_product): ?>
                <tr class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                    <td>
                        <?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?>
                    </td>
                    <td>
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    </td>
                    <td>
                        <?php $_stockItem = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product) ?>
                        <?php echo (int) $_stockItem->getQty() ?>
                    </td>
                    <td>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </td>
                    <td>
                        <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                    </td>
                </tr>
            <?php endforeach; ?>
    </table>
    <script type="text/javascript">decorateTable('products-list')</script>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>

<?php
    //set product collection on after blocks
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach($_afterChildren as $_afterChildName):
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        $_afterChild->setProductCollection($_productCollection);
    ?>
    <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>
